sudo: required
dist: trusty

language: node_js
cache: 
  - npm
  - directories:
    - ./build
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder


notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - os: linux
      node_js: lts/*
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        
    - os: osx
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: windows
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  allow_failures:
    - os: osx
  fast_finish: true

      # python: 3.4
      # node_js: lts/*

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then Powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine'; fi

  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python --version 2.7.2; fi

install:
  - npm install

script:
  - npm run build-quick
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run test-build; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then posershell -command 'npm run test-build'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo npm run test-build; fi

# after_success:
  # - npm run qb

#Deploy Configuration
# deploy:
#   provider: gcs
#   access_key_id: "GOOGW5SCWZHA42FT7THEI7TF"
#   secret_access_key: 
#     secure : "DZqKp2VkSfAFBiNCHOcuaGeuEp0I+n38rumvUP5IB0JNc1+nCvBo00k1y8f8PIrhHtJlGvOF3kAS2qZAFxVwpKjZE0wUdL0GTWppWBkqearuPdSX8Kn/N0tm0jXjYqgwSdF1gwDkU3S9CrSjL9rxuswNmLcbHUlNAr/fE49pQQq1f92NEPK/qoAaBBkaVeQsg2DbNca7TxBrIm6U0Up6xNAQmCio71JmC7Ezh0YESFxPT8I5Ng2TB7eaud3dwl1yqe/mODVk8AQ9OdfoSTA0PSRchTrH5Zi6a5Zl5U4Pps+5wdG/r1xA2u5UIF6OZ3TDCMD3++M0hHW/ij6PP773xi9Bwykycs1Qpr/dFxPD5WSL/Rlu76hvfzXTvIFePvu63GlMeXB3+ayTIi/KvRehVQpA51TdR7BteeMH16yPzrnVznwmQjBxV2ybl+Ui53ypLyyoupF/h/u1ggbtYA6mjpmdx+yXHcGPNAUsDu6QiEa0XcRWsYD/MgDwrSvUEtnnHhKq7X9Vm4KC0CW95Vv2C6QYBLEYlpjTfpnfcRyLGD0tDUY69VSp7TtZPqQdNh3i9wCzg+AYpJT3dQPBsVIgKnGavj1fK7xcAPPIzxWX1ZGXCofTUEXgDEohPVTE0mRs9pNv6LUQcvtUuyMucap0HhktAc6Ye9yUsbDM+zEmiHo="
#   bucket: "autoupdate.diymechatronics.com"
#   skip_cleanup: true
#   acl: public-read
#   file:
#     - build_$TRAVIS_OS_NAME.tar
#   on:
#     branch: release