sudo: required
dist: trusty
language: node_js
cache:
- npm
- directories:
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: Tm4Hp9fO/MB/b0t/r14XU2AYLPYFV7m0XzI4f0F652wiJ+ThWC/+cWlLsUYrXVNLvWe6Ry+ifZFV4u2tkbK07EN5HvmN27/BHg2PA7cnewrBN+BqJBAjK/U+yKN3L4Gl9N2xKKkBEUwxaeoxcCmiRlIRLnSWdFk3rSZyC3YDCAsduVZ7QX1dkiyX3no5aIZ7BN7G7zJyIIciwH+i9f6wET+7p5pO+Ypeb9avXVTA0oB7DhSXv+PcS/GljVNdSLolsxj44XtWut40Q4QnHamHwT2MgCewXnWD4k3x76UMy1axlyWmN8ezvXV7917gz+ufQ50ahV/92Mi5EoY2mfw1rFK+cAYPcoGNZbou8fVOhcfHcjDT2Xq8Ua9t9M6IPhCNCprSPybsy2riIEL1XAQD1auKs5CHuTTiB7jc7nkdsAUkH6kJbcmSEuudgdbq7oeKThL86oTW2GMfgJCx18KwJFuVWyHz1a0QusDSUYGQGIFgPNPe6ei4R0OzoH2W3MWrJG3U91bsraXCVI2NEWgf/u1UITrsS/vtFleAhCSOjnVtGOyoAs+FpLBKXnDnEZmQ3WTph6faEMgANInYcxPkLDf/lK2cjy4qNZjBiG+72FKSfDT6JBSurEv5QJyj13o1MNvlWqonoF9wLpGCAhCzVkn1KobFvhaMCGYLoL7JrDc=
matrix:
  include:
  - os: linux
    node_js: lts/*
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    compiler: clang
  allow_failures:
  - os: osx
  fast_finish: true
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - bsdtar
    - snapd
before_install:
- openssl aes-256-cbc -K $encrypted_56d791a64072_key -iv $encrypted_56d791a64072_iv
  -in ./dev-assets/travis-secrets.tar.enc -out ./dev-assets/travis-secrets.tar -d
# - openssl aes-256-cbc -K $encrypted_1248026558a0_key -iv $encrypted_1248026558a0_iv
#   -in ./dev-assets/secrets.tar.enc -out ./dev-assets/secrets.tar -d
- tar xvf ./dev-assets/travis-secrets.tar -C ./dev-assets
# - tar xvf ./dev-assets/secrets.tar -C ./dev-assets
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then base64 ./dev-assets/code-sign.p12 > ./dev-assets/envValue.txt;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then base64 -i ./dev-assets/code-sign.p12 -o
  ./dev-assets/envValue.txt; fi
- "if [ $TRAVIS_BRANCH == \"master\" ] || [ $TRAVIS_BRANCH == \"master-all\" ]; then\n
  \   export QUARK_RUN_BUILD=true;\n  else \n    export QUARK_RUN_BUILD=false;\nfi\n"
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then sudo
  snap install snapcraft --classic; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then export
  DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- echo $QUARK_RUN_BUILD
- npm install
before_script:
- node --version
- npm --version
script:
- npm run build-ci
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run test-ci; fi
after_success:
- npm run upload-ci
- ls -la ./build
deploy:
  provider: releases
  api_key:
    secure: w2jOev3cPNKViXmlN89mnS+O+ec3BlZH6toIz6I5y5v/4r38myfFpmFu/x+x2szGQFgzMTVShZ6MvGHcWB9VICPUIoruWymGm1Ivc9jdMcj6UQ2YW2eF9DQK2gIfJzC6quGtntoHyyfn1yr8pPnAfCYcs62o573dJYHJSYkjUIkCCEki/Yv/jAQdz392b84PPwA14c/nkm0CpuuF8UXQXPXxwHt2yNyNHD5FSL8/tQEGAECMtKdCWzkf6qcPfxuhbHCZl4zlFD4DknihDEDBGZ6NqCdM3lWhsiKRK7CPXbl1yBCQqTEEfS5l231sC1YN+I5bVYiCqBlcZRLM7zzCDUUBgkOJmaoOxJe1SdKlnPBQIyFWMJR6xaWEF4T+S/USNRrDi2jCmfxV8Fpj/DtYVXEvy1mZAI7u42GvNit71PNcz2O932KtC0YZej+gSwnPeuzoih3jHxfXL6hvD9X2qNPgXmR6FlMcULP/W82obQJLHbg+HByxhPamE7iy7nvA/LLunQ9XqEJL4N31Pyuv28n6ErD/W3U/WJdoEctPZM8Za/qmOgKobE/hKA3HN8ABIA09o8FZXX4yho/AXHHiHGBrC23Ww2P8/GAap7a5NMrKhNkqrK70UFT3jfIcXNQoM10gUF6HBMHWIl+crdnT7Ib2440i1ZjtDgEYfWjWAnM=
  file_glob: true
  skip_cleanup: true
  overwrite: true
  draft: true
  prerelease: true
  name: Current_CI_Build
  tag: Current_CI_Build
  target_commitish: master
  file:
  - build/*.deb
  - build/*.gz
  - build/*.AppImage
  - build/*.yml
  on:
    all_branches: true
    repo: Nishkalkashyap/Quark-electron
