sudo: required
dist: trusty
language: node_js
cache:
- npm
- directories:
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: GPI5TqVmDKctjLio7aEY9fWOHFjj9+FXff1wdyo/8D4RaJlwfZjh4Z8n7pFxgp8R5kEOIGMWXXjetaGIazUT0KCL4vwbujk3Gt0NWK5fYGRNq1uY/abHm9Q1fGhUJZXB+Eb4xxRjl3seLai5JoIdaRc8m4qT7OnfYntgAScfuyPmKfxRUsdfFmIUbaPCyIMRvaie5Ce1RytjY/006xYlOqtreayc5LGWJIKbvRSDYdoKsiuTU2qcgMffaRHAzsR/Ffx7odlWnanhGrfN6XuPiEQHGdgF5G59nTV2vBnvexB/Z2A9wFt7HZAbcitWTq/rh/TrXtlbRJGJA133XTbAR54JRRqCQU+pj1t3tAj4b4hezIKxZkWww9WDj0Tmsk8COdT5fiLDqBvKt11V+JrkLFHIj+K4CABdOWUBbMrKwpzv4Z5Q9B7IbJPjumIBKdEdxqOmbYk4chwHXu0B/SaqbH7y4laLKPlGlHLooGyZGK7On6Fk+zW5VMEGXEvcSvV8dnAN8HlPe0vlSetuzt85dX5GbONAj2+KqioTO2ahPTgxWVgJL6jlwNol7Sif6MGwQH7L27HqukuMQDMf7WqymXqIdmPbVngayvQ54ZSq8IngeX7EGK5sH4jMbD3HuQ6gJvL773vL0ah3PTMJEbmYdqYVSB8/FLB31rGvY8QkMXc=
matrix:
  include:
  - os: linux
    node_js: lts/*
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    compiler: clang
  allow_failures:
  - os: osx
  fast_finish: true
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - bsdtar
    - snapd
before_install:
- openssl aes-256-cbc -K $encrypted_1248026558a0_key -iv $encrypted_1248026558a0_iv
  -in ./dev-assets/secrets.tar.enc -out ./dev-assets/secrets.tar -d
- tar xvf ./dev-assets/secrets.tar -C ./dev-assets
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then base64 ./dev-assets/code-sign.p12 > ./dev-assets/envValue.txt;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then base64 -i ./dev-assets/code-sign.p12 -o
  ./dev-assets/envValue.txt; fi
- "if [ $TRAVIS_BRANCH == \"master\" ] || [ $TRAVIS_BRANCH == \"master-all\" ]; then\n
  \   export QUARK_RUN_BUILD=true;\n  else \n    export QUARK_RUN_BUILD=false;\nfi\n"
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then sudo
  snap install snapcraft --classic; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then export
  DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- echo $QUARK_RUN_BUILD
- npm install
before_script:
- node --version
- npm --version
script:
- npm run build-ci
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run test-ci; fi
after_success:
- npm run upload-ci
- ls -la ./build
