sudo: required
dist: trusty
language: node_js
cache:
- npm
- directories:
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
notifications:
  email:
    on_success: never
    on_failure: change
matrix:
  include:
  - os: linux
    node_js: lts/*
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    compiler: clang
  - os: osx
    node_js: lts/*
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  allow_failures:
  - os: osx
  fast_finish: true
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - bsdtar
    - snapd
before_install:
- openssl aes-256-cbc -K $encrypted_1248026558a0_key -iv $encrypted_1248026558a0_iv
  -in ./dev-assets/secrets.tar.enc -out ./dev-assets/secrets.tar -d
- tar xvf ./dev-assets/secrets.tar -C ./dev-assets
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then base64 ./dev-assets/code-sign.p12 > ./dev-assets/envValue.txt; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then base64 -i ./dev-assets/code-sign.p12 -o ./dev-assets/envValue.txt; fi


- "if [ $TRAVIS_BRANCH == \"master\" ] || [ $TRAVIS_BRANCH == \"master-all\" ]; then\n
  \   export QUARK_RUN_BUILD=true;\n  else \n    export QUARK_RUN_BUILD=false;\nfi\n"
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then sudo
  snap install snapcraft --classic; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $QUARK_RUN_BUILD == "true" ]; then export
  DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- echo $QUARK_RUN_BUILD
- npm install
before_script:
- node --version
- npm --version
script:
- npm run build-ci
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run test-ci; fi
after_success:
- npm run upload-ci
- ls -la ./build
