# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64

image: Visual Studio 2017

# init:
#   - yarn config set msvs_version 2017 # we need this to build `pty.js`
#   - npm config set msvs_version 2017 # we need this to build `pty.js`

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.electron-gyp'
  - '%USERPROFILE%\.node-gyp'
  - '%USERPROFILE%\.windows-build-tools'

install:
  - ps: Install-Product node 10.2.0 x64
  - npm install --global npm@latest
  - npm install --global node-gyp@latest
  - npm install --global --production windows-build-tools
  # - choco install python --version 2.7.2
  - set CI=true
  - npm install

# build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm run build-quick
  - npm run test-build