# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml
os: unstable

environment:
  matrix:
    - platform: x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.electron-gyp'
  - '%USERPROFILE%\.node-gyp'
  - '%USERPROFILE%\.windows-build-tools'

install:
  - ps: Install-Product node 10.2.0 x64
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%	  
  - npm i -g node-gyp && node-gyp clean
  - npm install --global --production windows-build-tools
  - npm install

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm run build-quick
  - npm run test-build